let containerLegend = d3.select("#legend")
  .append("svg")
  .attr("height", 150)
  .attr("width", 800)

// legend rectangles
containerLegend.append("rect").attr("x",10).attr("y",10).attr("width", 10).attr("height", 10).style("fill", "#D9A398")
containerLegend.append("rect").attr("x",10).attr("y",35).attr("width", 10).attr("height", 10).style("fill", "#4F96C4")
containerLegend.append("rect").attr("x",10).attr("y",60).attr("width", 10).attr("height", 10).style("fill", "#6A3D9A")
containerLegend.append("rect").attr("x",10).attr("y",85).attr("width", 10).attr("height", 10).style("fill", "#F79B5D")
containerLegend.append("rect").attr("x",10).attr("y",110).attr("width", 10).attr("height", 10).style("fill", "#A788C0")
containerLegend.append("rect").attr("x",250).attr("y",10).attr("width", 10).attr("height", 10).style("fill", "#A6CEE3")
containerLegend.append("rect").attr("x",250).attr("y",35).attr("width", 10).attr("height", 10).style("fill", "#4995A8")
containerLegend.append("rect").attr("x",250).attr("y",60).attr("width", 10).attr("height", 10).style("fill", "#FDA33F")
containerLegend.append("rect").attr("x",250).attr("y",85).attr("width", 10).attr("height", 10).style("fill", "#EF595A")
containerLegend.append("rect").attr("x",250).attr("y",110).attr("width", 10).attr("height", 10).style("fill", "#5D9E43")
containerLegend.append("rect").attr("x",490).attr("y",10).attr("width", 10).attr("height", 10).style("fill", "#DE9A89")
containerLegend.append("rect").attr("x",490).attr("y",35).attr("width", 10).attr("height", 10).style("fill", "#E63127")
containerLegend.append("rect").attr("x",490).attr("y",60).attr("width", 10).attr("height", 10).style("fill", "#A7D78D")
containerLegend.append("rect").attr("x",490).attr("y",85).attr("width", 10).attr("height", 10).style("fill", "#69BB54")
containerLegend.append("rect").attr("x",490).attr("y",110).attr("width", 10).attr("height", 10).style("fill", "#FB820F")

// legend text
containerLegend.append("text").attr("x",30).attr("y",20).text("Sports, Exercise, and Recreation").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",30).attr("y",45).text("Personal Care").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",30).attr("y",70).text("Sleep").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",30).attr("y",95).text("Socializing, Relaxing, and Leisure").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",30).attr("y",120).text("Household Activities").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",270).attr("y",20).text("Work").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",270).attr("y",45).text("Professional & Personal Care Services").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",270).attr("y",70).text("Eating and Drinking").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",270).attr("y",95).text("Caring For Household Member").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",270).attr("y",120).text("Consumer Purchases").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",510).attr("y",20).text("Other").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",510).attr("y",45).text("Caring For Nonhousehold Members").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",510).attr("y",70).text("Education").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",510).attr("y",95).text("Volunteer").attr("class", "legend_item_text")
containerLegend.append("text").attr("x",510).attr("y",120).text("Religious and Spiritual").attr("class", "legend_item_text")
